import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Event Commander",
  description: "Generated by create next app",
};

import { Navigation } from "@/components/navigation";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";
import { getDiscordUser, getDiscordAvatarUrl } from "@/lib/discord";
import { Providers } from "@/components/providers";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  let userAvatarUrl = undefined;
  if (session?.user) {
    // Force logout if account is disabled
    if ((session.user as any).isActive === false) {
      // We can't easily signout from server component, but we can prevent rendering
      // and the client side logic (if added) or middleware could handle it.
      // For now, let's treat them as unauthenticated or redirect to a block page.
      // Since we are in root layout, this might be tricky.
      // Better approach: Middleware should handle this if possible, OR
      // we use a client component to effect the signout.
    }

    if ((session.user as any).discordId) {
      const discordUser = await getDiscordUser((session.user as any).discordId);
      if (discordUser?.avatar) {
        userAvatarUrl = getDiscordAvatarUrl(discordUser.id, discordUser.avatar) ?? undefined;
      }
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers session={session}>
          <div className="flex flex-col min-h-screen bg-neutral-950 text-neutral-50">
            <Navigation />
            <main className="flex-1 w-full flex flex-col">
              {children}
            </main>
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
